# PHP 7.4 FPM Demo
server {
    listen 80;
    server_name php74.local.pandora;

    set $upstream_php74 demo-php74:9000;

    location / {
        fastcgi_pass $upstream_php74;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        include fastcgi_params;
    }
}
