# PHP 8.3 FPM Demo
server {
    listen 80;
    server_name php83.local.pandora;

    set $upstream_php83 demo-php83:9000;

    location / {
        fastcgi_pass $upstream_php83;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        include fastcgi_params;
    }
}
